# ==============================================
# Framework Configuration
# ==============================================

# Application under test
url=https://www.demoblaze.com
browser=chrome
implicit.wait=10
explicit.wait=20
page.load.timeout=30

# Execution mode: local or headless
headless=false

# Excel test data path
excel.path=src/test/resources/testdata/TestData.xlsx

# Reporting
report.path=reports/ExtentReport.html
screenshot.path=reports/screenshots/
